import Link from "next/link";
import { LocalizedText } from "@/components/i18n/localized-text";
import { canonicalUrl } from "@/lib/site";

type Props = { eyebrow: string; title: string; intro: string; pathname?: string; sections: Array<{ id?: string; title: string; body: string }>; relatedLinks?: Array<{ href: string; label: string }> };
export function InfoPage({ eyebrow, title, intro, pathname, sections, relatedLinks = [] }: Props) {
  const breadcrumbs = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: canonicalUrl("/").toString() }, { "@type": "ListItem", position: 2, name: title, item: canonicalUrl(pathname ?? "/").toString() }] };
  return <main id="main-content" className="bg-[#f7f5f1]">{pathname ? <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbs) }} /> : null}<section className="border-b border-stone-300 bg-[#0d2b3f] px-5 py-12 text-white sm:px-8 lg:px-10 lg:py-16"><div className="mx-auto max-w-[1180px]"><nav aria-label="Breadcrumb" className="mb-7 text-sm text-stone-300"><Link href="/" className="underline-offset-4 hover:underline">Home</Link><span aria-hidden="true"> / </span><span aria-current="page">{title}</span></nav><p className="section-label text-stone-300">{eyebrow}</p><h1 className="mt-3 max-w-3xl font-serif text-[clamp(2.8rem,6vw,5.25rem)] leading-[.95] tracking-[-.025em]">{title}</h1><p className="mt-5 max-w-2xl text-base leading-7 text-stone-200 sm:text-lg">{intro}</p></div></section><section className="mx-auto grid max-w-[1180px] gap-8 px-5 py-10 sm:px-8 lg:grid-cols-[.68fr_1.32fr] lg:px-10 lg:py-16"><div><p className="section-label text-stone-500">JS Meilai</p><p className="mt-3 max-w-[18ch] font-serif text-2xl text-[#0d2b3f] sm:text-3xl"><LocalizedText k="common.brandTagline" fallback="Clear direction. Practical sourcing." /></p><Link href="/contact/#rfq" className="mt-6 inline-flex min-h-11 items-center bg-[#0d2b3f] px-5 text-sm font-medium text-white"><LocalizedText k="common.sendEnquiry" fallback="Send procurement enquiry" /></Link></div><div className="divide-y divide-stone-300 border-y border-stone-300">{sections.map((section) => <article id={section.id} key={section.title} className="py-6"><h2 className="font-serif text-2xl text-[#0d2b3f] sm:text-3xl">{section.title}</h2><p className="mt-3 max-w-2xl leading-7 text-stone-700">{section.body}</p></article>)}</div></section><div className="mx-auto flex max-w-[1180px] flex-wrap gap-x-6 gap-y-3 px-5 pb-12 text-sm sm:px-8 lg:px-10">{relatedLinks.map((link) => <Link key={link.href} href={link.href} className="underline underline-offset-4">{link.label}</Link>)}</div></main>;
}
